AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    # having the table name referencing prod or dev stage from the serverless.yml(self) file
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
